# postgreSQL
version: "3.1"

services:
  database:
    image: postgres
    # restart: always # これがあると、dockerソフト起動時にrunningになっちゃう。
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
        - POSTGRES_HOST_AUTH_METHOD=trust #追加した
