# TaskEXでファイルと下記コードをコピペ
services:
  - type: web
    name: wonderful-editor
    env: ruby
    region: singapore
    # plan: free # 無料版
    plan: starter #Render.comの有料プラン（プラン名）
    # branch: master
    branch: main
    numInstances: 1
    healthCheckPath: /
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-wonderful-editor
          property: connectionString
    autoDeploy: false

databases:
  - name: postgresql-wonderful-editor
    region: singapore
    # plan: free
    plan: starter #Render.comの有料プラン（プラン名）
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere # 学習用
